services:
  db:
    image: postgres:18-trixie
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - course
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
volumes:
  pgdata:
  keycloak-data:

networks:
  course:
    driver: bridge